/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DebianRepositoryIndexCompression = "bz2" | "gz" | "lzma" | "xz";

export type DebianRepositoryPackageStagingStatus = "add" | "remove";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _SqlxMigrations {
  checksum: Buffer;
  description: string;
  execution_time: Int8;
  installed_on: Generated<Timestamp>;
  success: boolean;
  version: Int8;
}

export interface DebianRepository {
  codename: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  distribution: string;
  id: Generated<Int8>;
  label: string | null;
  origin: string | null;
  s3_bucket: string;
  s3_prefix: string;
  suite: string;
  updated_at: Generated<Timestamp>;
  uri: string;
  version: string | null;
}

export interface DebianRepositoryArchitecture {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  repository_id: Int8;
  updated_at: Generated<Timestamp>;
}

export interface DebianRepositoryComponent {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  repository_id: Int8;
  updated_at: Generated<Timestamp>;
}

export interface DebianRepositoryIndexContents {
  component_id: Int8;
  compression: DebianRepositoryIndexCompression | null;
  contents: Buffer;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  md5sum: string;
  repository_id: Int8;
  sha1sum: string;
  sha256sum: string;
  size: Int8;
  updated_at: Generated<Timestamp>;
}

export interface DebianRepositoryIndexPackages {
  architecture_id: Int8;
  component_id: Int8;
  compression: DebianRepositoryIndexCompression | null;
  contents: Buffer;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  md5sum: string;
  repository_id: Int8;
  sha1sum: string;
  sha256sum: string;
  size: Int8;
  updated_at: Generated<Timestamp>;
}

export interface DebianRepositoryIndexRelease {
  clearsigned: string | null;
  codename: string;
  contents: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  detached: string | null;
  id: Generated<Int8>;
  label: string | null;
  origin: string | null;
  repository_id: Int8;
  suite: string;
  updated_at: Generated<Timestamp>;
  version: string | null;
}

export interface DebianRepositoryPackage {
  architecture_id: Int8;
  component_id: Int8;
  conflicts: string | null;
  created_at: Generated<Timestamp>;
  depends: string | null;
  description: string;
  filename: string;
  homepage: string | null;
  id: Generated<Int8>;
  installed_size: Int8 | null;
  maintainer: string;
  md5sum: string;
  package: string;
  paragraph: Json;
  priority: string | null;
  provides: string | null;
  recommends: string | null;
  replaces: string | null;
  repository_id: Int8;
  section: string | null;
  sha1sum: string;
  sha256sum: string;
  size: Int8;
  staging_status: DebianRepositoryPackageStagingStatus | null;
  updated_at: Generated<Timestamp>;
  version: string;
}

export interface DB {
  _sqlx_migrations: _SqlxMigrations;
  debian_repository: DebianRepository;
  debian_repository_architecture: DebianRepositoryArchitecture;
  debian_repository_component: DebianRepositoryComponent;
  debian_repository_index_contents: DebianRepositoryIndexContents;
  debian_repository_index_packages: DebianRepositoryIndexPackages;
  debian_repository_index_release: DebianRepositoryIndexRelease;
  debian_repository_package: DebianRepositoryPackage;
}
