BEGIN;

-- https://wiki.debian.org/DebianRepository/Format

-- BEGIN REPOSITORY TABLES.

CREATE TABLE debian_repository (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Uniquely identifying fields for the repository.
  uri TEXT NOT NULL,
  distribution TEXT NOT NULL,
  UNIQUE (uri, distribution),

  -- Metadata fields for the top-level Release file. These are the _current_
  -- (i.e. _staging_) values, not necessarily the ones in production.
  origin TEXT NOT NULL,
  label TEXT NOT NULL,
  suite TEXT NOT NULL,
  codename TEXT NOT NULL,
  description TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE debian_repository_architecture (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES debian_repository(id),

  -- TODO: Since there's only a certain set of officially supported
  -- architectures for Debian, should this table be an ENUM instead?
  name TEXT NOT NULL,
  UNIQUE (repository_id, name),

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE debian_repository_component (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES debian_repository(id),

  name TEXT NOT NULL,
  UNIQUE (repository_id, name),

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- END REPOSITORY TABLES.

-- BEGIN INDEX TABLES.
--
-- These tables represent the various index files. Their checksums are cached
-- here to generate the Release file.

CREATE TABLE debian_repository_index_release (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES debian_repository(id),
  UNIQUE (repository_id),

  -- Metadata fields for the Release index. These are the values used to
  -- actually generate this file that's hosted in production.
  origin TEXT NOT NULL,
  label TEXT NOT NULL,
  suite TEXT NOT NULL,
  codename TEXT NOT NULL,
  description TEXT NOT NULL,

  -- The contents of the `Release` file.
  contents TEXT NOT NULL,

  -- GPG signatures.
  clearsigned TEXT,
  detached TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE debian_repository_index_compression AS ENUM ('xz', 'gz', 'bz2', 'lzma');

CREATE TABLE debian_repository_index_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES debian_repository(id),

  -- Packages indexes' file paths are uniquely identified by (component, arch).
  component_id BIGINT NOT NULL REFERENCES debian_repository_component(id),
  architecture_id BIGINT NOT NULL REFERENCES debian_repository_architecture(id),
  UNIQUE (repository_id, component_id, architecture_id),

  compression debian_repository_index_compression,
  size BIGINT NOT NULL,
  contents BYTEA NOT NULL,

  md5sum TEXT NOT NULL,
  sha1sum TEXT NOT NULL,
  sha256sum TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE debian_repository_index_contents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES debian_repository(id),

  -- Contents indexes' file paths are uniquely identified by component.
  component_id BIGINT NOT NULL REFERENCES debian_repository_component(id),
  UNIQUE (repository_id, component_id),

  compression debian_repository_index_compression,
  size BIGINT NOT NULL,
  contents BYTEA NOT NULL,

  md5sum TEXT NOT NULL,
  sha1sum TEXT NOT NULL,
  sha256sum TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- END INDEX TABLES.

-- BEGIN PACKAGE TABLES.
--
-- These tables represent the packages in the repository.

-- TODO: Add 'replace' type?
CREATE TYPE debian_repository_package_staging_status AS ENUM ('add', 'remove');

CREATE TABLE debian_repository_package (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES debian_repository(id),
  architecture_id BIGINT NOT NULL REFERENCES debian_repository_architecture(id),
  -- TODO: For now, different components mean different packages uploaded to
  -- different filenames (using the standard pool format). But we should
  -- investigate whether we can avoid this redundancy, perhaps by using
  -- redirects or storing filenames by hash (does `Filename: ` support non-pool
  -- paths?).
  component_id BIGINT NOT NULL REFERENCES debian_repository_component(id),

  -- If set, this is a _new_ change in the staging area. This package is either
  -- being added or removed.
  staging_status debian_repository_package_staging_status,

  -- For a list of available fields, see:
  -- 1. https://wiki.debian.org/DebianRepository/Format#A.22Packages.22_Indices
  -- 2. https://www.debian.org/doc/debian-policy/ch-controlfields.html#debian-binary-package-control-files-debian-control
  package TEXT NOT NULL,
  version TEXT NOT NULL,
  priority TEXT,
  section TEXT,
  installed_size BIGINT,
  maintainer TEXT NOT NULL,
  description TEXT NOT NULL,
  homepage TEXT,

  -- Within the same component, repositories do not contain duplicate packages
  -- with the same (name, version, arch). See:
  -- https://wiki.debian.org/DebianRepository/Format#Duplicate_Packages
  UNIQUE (repository_id, component_id, package, version, architecture_id),

  -- Free-form { [key: string]: string } containing all control file fields.
  -- This encapsulates the presences of extra fields sometimes, like `License`
  -- or `Vendor`.
  paragraph JSONB NOT NULL,

  depends TEXT,
  recommends TEXT,
  conflicts TEXT,
  provides TEXT,
  replaces TEXT,

  -- TODO: These checksums are not currently unique because the same package
  -- stored at different filenames is currently considered a different package
  -- right now. We should investigate whether we can avoid this redundancy.
  filename TEXT NOT NULL,
  size BIGINT NOT NULL,
  md5sum TEXT NOT NULL,
  sha1sum TEXT NOT NULL,
  sha256sum TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- END PACKAGE TABLES.

COMMIT;
