BEGIN;

-- A tenant is roughly an organization, which is a single account that pays for
-- us. A tenant can be associated with multiple human users, although we don't
-- model those users individually right now.
CREATE TABLE attune_tenant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  display_name TEXT NOT NULL,

  -- The prefix for S3 objects for this tenant.
  s3_prefix TEXT NOT NULL UNIQUE,
  -- The managed cloud subdomain for this tenant (i.e. their repositories that
  -- don't use custom domains will be hosted at `*.<subdomain>.attunehq.com`).
  subdomain TEXT NOT NULL UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- An API token for a tenant.
CREATE TABLE attune_tenant_api_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES attune_tenant(id),

  -- This is just for human readability purposes.
  name TEXT NOT NULL,
  -- This is a bcrypt API token hash.
  token BYTEA NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
