BEGIN;

-- https://wiki.debian.org/DebianRepository/Format

CREATE TABLE debian_repository (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uri TEXT NOT NULL,
  distribution TEXT NOT NULL,
  active_release_id BIGINT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE debian_repository_release (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES debian_repository(id),

  origin TEXT NOT NULL,
  label TEXT NOT NULL,
  suite TEXT NOT NULL,
  codename TEXT NOT NULL,
  description TEXT NOT NULL,

  -- The contents of the `Release` file.
  contents TEXT,
  pgp_signature_hash TEXT,
  pgp_signature TEXT,

  -- This goes stale as soon as any package changes.
  stale BOOLEAN NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- https://squawkhq.com/docs/adding-foreign-key-constraint
ALTER TABLE debian_repository ADD CONSTRAINT debian_repository_active_release_id_fkey FOREIGN KEY (active_release_id) REFERENCES debian_repository_release(id) NOT VALID;

CREATE TABLE debian_repository_architecture (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id BIGINT NOT NULL REFERENCES debian_repository_release(id),

  name TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE debian_repository_component (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id BIGINT NOT NULL REFERENCES debian_repository_release(id),

  name TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE debian_repository_index_compression AS ENUM ('none', 'xz', 'gz', 'bz2', 'lzma');

-- This represents all sorts of indexes. This is mainly used to cache the
-- checksums for generating the Release file.
CREATE TABLE debian_repository_packages_index (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id BIGINT NOT NULL REFERENCES debian_repository_release(id),
  component_id BIGINT NOT NULL REFERENCES debian_repository_component(id),
  architecture_id BIGINT NOT NULL REFERENCES debian_repository_architecture(id),

  format debian_repository_index_compression NOT NULL,
  size BIGINT NOT NULL,
  contents BYTEA NOT NULL,

  md5sum TEXT NOT NULL,
  sha1sum TEXT NOT NULL,
  sha256sum TEXT NOT NULL,

  -- This goes stale when any package within scope changes.
  stale BOOLEAN NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE debian_repository_contents_index (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id BIGINT NOT NULL REFERENCES debian_repository_release(id),
  component_id BIGINT NOT NULL REFERENCES debian_repository_component(id),

  format debian_repository_index_compression NOT NULL,
  size BIGINT NOT NULL,
  contents BYTEA NOT NULL,

  md5sum TEXT NOT NULL,
  sha1sum TEXT NOT NULL,
  sha256sum TEXT NOT NULL,

  -- This goes stale when any package within scope changes.
  stale BOOLEAN NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE debian_repository_package (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id BIGINT NOT NULL REFERENCES debian_repository_release(id),
  architecture_id BIGINT NOT NULL REFERENCES debian_repository_architecture(id),
  component_id BIGINT NOT NULL REFERENCES debian_repository_component(id),

  -- For a list of available fields, see:
  -- 1. https://wiki.debian.org/DebianRepository/Format#A.22Packages.22_Indices
  -- 2. https://www.debian.org/doc/debian-policy/ch-controlfields.html#debian-binary-package-control-files-debian-control
  package TEXT NOT NULL,
  version TEXT NOT NULL,
  priority TEXT,
  section TEXT,
  installed_size BIGINT,
  maintainer TEXT NOT NULL,
  description TEXT NOT NULL,
  homepage TEXT,

  -- Free-form { [key: string]: string } containing all control file fields.
  -- This encapsulates the presences of extra fields sometimes, like `License`
  -- or `Vendor`.
  paragraph JSONB NOT NULL,

  depends TEXT,
  recommends TEXT,
  conflicts TEXT,
  provides TEXT,
  replaces TEXT,

  filename TEXT NOT NULL,
  size BIGINT NOT NULL,
  md5sum TEXT NOT NULL,
  sha1sum TEXT NOT NULL,
  sha256sum TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- This is primarily used for generating Contents indices.
CREATE TABLE debian_repository_package_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id BIGINT NOT NULL REFERENCES debian_repository_package(id),

  filepath TEXT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;

BEGIN;
ALTER TABLE debian_repository VALIDATE CONSTRAINT debian_repository_active_release_id_fkey;
COMMIT;
