name: Build docs site

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/site/** # Only trigger when changes are made to docs directory.

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: docs/site/package-lock.json 

      - name: Install dependencies
        run: npm ci
        working-directory: docs/site
      - name: Test build website
        run: npm run build
        working-directory: docs/site

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-site-preview
          path: docs/site/build
          retention-days: 14
