# Workflows that run on tags. These are primarily CD tasks for cutting
# production release builds.
name: Tag

on:
  push:
    tags: ["v*"]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/*.json"
      - "**/*.lock"
      - "**/.gitignore"
      - "**/LICENSE"

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  macos-notarize:
    name: Build and notarize Attune CLI macOS binary
    runs-on: macos-latest # macOS 14 ARM64
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup show

      - name: Remove empty EE crate
        run: rm -r ./packages/attune-ee

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2.8.0
        with:
          cache-workspace-crates: true
          cache-all-crates: true

      - name: Build macOS binary
        run: cargo build --bin attune --release

      - name: Import signing certificate
        env:
          APPLE_SIGNING_CERTIFICATE: ${{ secrets.APPLE_SIGNING_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          echo -n "$APPLE_SIGNING_CERTIFICATE" | base64 --decode -o $RUNNER_TEMP/certificate.p12
          security create-keychain -p "$APPLE_CERTIFICATE_PASSWORD" $RUNNER_TEMP/build.keychain
          security default-keychain -s $RUNNER_TEMP/build.keychain
          security unlock-keychain -p "$APPLE_CERTIFICATE_PASSWORD" $RUNNER_TEMP/build.keychain
          security import $RUNNER_TEMP/certificate.p12 -k $RUNNER_TEMP/build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$APPLE_CERTIFICATE_PASSWORD" $RUNNER_TEMP/build.keychain
          rm $RUNNER_TEMP/certificate.p12

      - name: Sign binary
        env:
          APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
        run: |
          codesign --sign "$APPLE_DEVELOPER_ID" \
                   --timestamp \
                   --options=runtime \
                   --force \
                   target/release/attune

      - name: Store notarization credentials
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          xcrun notarytool store-credentials "notarytool-password" \
                  --apple-id "$APPLE_ID" \
                  --team-id "$APPLE_DEVELOPER_ID" \
                  --password "$APPLE_APP_SPECIFIC_PASSWORD"

      - name: Create ZIP for notarization
        run: zip $RUNNER_TEMP/attune-macos.zip target/release/attune

      # Can add --wait to tell notarytool to exit only after the Notary service finishes processing the submission.
      - name: Submit for notarization
        run: |
          xcrun notarytool submit $RUNNER_TEMP/attune-macos.zip \
                  --keychain-profile "notarytool-password"

      # TODO: Add xcrun stapler step in the future so the binary can be validated without internet access.

      - name: Upload notarized binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-binaries
          path: target/release/attune

  publish:
    name: Production build and publish draft release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build and test binaries.
      - name: Install Rust
        run: rustup show

      - name: Remove empty EE crate
        run: rm -r ./packages/attune-ee

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2.8.0
        with:
          cache-workspace-crates: true
          cache-all-crates: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpg-error-dev libgpgme-dev pkg-config

      - name: Build binaries
        run: cargo build --workspace --all-targets --all-features --release

      - name: Run tests
        run: cargo test --workspace --all-targets --all-features --release

      # Download notarized macOS binary
      - name: Download notarized macOS binary
        uses: actions/download-artifact@v4
        with:
          name: attune-macos-notarized
          path: /tmp/macos-binary

      # Publish GitHub pre-release.
      - name: Copy and rename release assets
        run: |
          mkdir -p /tmp/release
          cp target/release/attune /tmp/release/attune-${{ github.ref_name }}_${{ runner.os }}-${{ runner.arch }}
          cp target/release/attune-server /tmp/release/attune-server-${{ github.ref_name }}_${{ runner.os }}-${{ runner.arch }}
          cp /tmp/macos-binary/attune /tmp/release/attune-${{ github.ref_name }}_macOS-ARM64

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          preserve_order: true
          generate_release_notes: true
          files: /tmp/release/*

      # Publish Docker image.
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: docker-build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/attune/Dockerfile
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.docker-build-and-push.outputs.digest }}
          push-to-registry: true
